### ISSUE TITLE
Buat tampilan data Dosen

### ISSUE THREAD

**Issue by ravieazharie15** [ravieazharie15/TugasPBW11#1]
Tolong buatkan sebuah tampilan untuk menampilkan data Dosen

**Comment by ahmadsofian15** [comment]
Baik, saya akan segera buat

**Comment by ahmadsofian15** [comment]
Saya sudah buat tampilan untuk menampilkan data dosen

**Comment by ravieazharie15** [comment]
oke saya sudah lihat, itu bagus dan sesuai
